# Generated by Django 4.0.5 on 2022-06-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_machinery_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinery',
            name='availability',
            field=models.CharField(max_length=5),
        ),
    ]
