# Generated by Django 4.0.5 on 2022-06-22 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order_user_id_profile_owner_post_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinery',
            name='forklifting_pay_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machinery',
            name='owner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machinery',
            name='planting_pay_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machinery',
            name='ploughing_pay_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machinery',
            name='transport_pay_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
