# Generated by Django 4.0.5 on 2022-06-22 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_machinery_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='machinery_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.machinery'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
