# Generated by Django 4.0.5 on 2022-06-22 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_machinery_forklifting_pay_rate_machinery_owner_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='public',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.DeleteModel(
            name='Public',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
