# Generated by Django 4.0.5 on 2022-06-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_feedback_email_feedback_machinery_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
    ]
